# Generated by Django 4.2.5 on 2023-09-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
