# Generated by Django 4.2.5 on 2023-09-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
