# Generated by Django 4.2.5 on 2023-09-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
