# Generated by Django 4.2.5 on 2023-09-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0002_users_detail_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_detail_child',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_details_child', to='serializers_app.user_details'),
            preserve_default=False,
        ),
    ]
