# Generated by Django 4.2.5 on 2023-09-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0003_users_detail_child_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user_id',
            new_name='id',
        ),
    ]
