# Generated by Django 4.2.5 on 2023-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0005_address_delete_users_detail_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='PIN_code',
            field=models.IntegerField(),
        ),
    ]
