# Generated by Django 4.2.5 on 2023-09-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0009_alter_user_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_details_child', to='serializers_app.user_details'),
        ),
    ]
