# Generated by Django 4.2.5 on 2023-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0010_alter_address_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
            ],
        ),
    ]
