# Generated by Django 4.2.5 on 2023-09-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0011_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
