# Generated by Django 4.2.5 on 2023-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializers_app', '0012_alter_course_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_on',
            field=models.CharField(max_length=200),
        ),
    ]
